import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import { TRPCReactProvider } from '@/trpc/react';
import { Providers } from '@/app/provaders';

export const metadata: Metadata = {
	title: 'Kirdro App',
	description: 'Generated by create-t3-app and Kirdro',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en' className={`${GeistSans.variable}`}>
			<body>
				<Providers>
					<TRPCReactProvider>{children}</TRPCReactProvider>
				</Providers>
			</body>
		</html>
	);
}
